# Generated by Django 2.2.6 on 2022-06-11 22:52

from django.db import migrations, models

import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220527_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[posts.validators.clean_text], verbose_name='Содержание'),
        ),
    ]
